{
    "openapi": "3.0.0",
    "info": {
        "title": "API de cadastro para pessoas em situação de vulnerabilidade social",
        "description": "Essa API tem como objetivo fazer o cadastro de pessoas que precisam de auxílio, por estar passando necessidades.",
        "termsOfService": "localhost:9095/terms/",
        "contact": {
            "email": "hannahcassia@gmail.com"
        },
        "version": "1.0.0"
    },
    "servers": [
        {
            "url":"localhost:9095/",
            "description": "API Cestas Solidárias"
    }
],
"tags": [
    {
        "name": "Beneficiados",
        "description": "Manipulação das Rotas dos Beneficiados"
    },
    {
        "name": "Doadores",
        "description": "Manipulação das Rotas dos Doadores"
    }
],
"paths": {
    "/users/create": {
        "post": {
            "summary": "Cadastro de Beneficiados",
            "description": "Essa rota será responsável por cadastrar um novo usuário que precisa de ajuda",
            "tags": ["Beneficiados"],
            "requestBody": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Beneficiados"
                        },
                        "example": {
                            "Beneficiados": {
                                "value": {
                                    "_id": "61b3c7936897b5137880ba5a",
                                    "name": "Leandro",
                                    "nickname": "Henrique",
                                    "email": "leandohq@hotmail.com",
                                    "celular": 81998526547,
                                    "whatsapp": true,
                                    "bairro": "cordeiro",
                                    "pix": "81998526547",
                                    "termosDeUso": true,
                                    "informacao": "Necessito de doações pois estou desempregado e tenho família para alimentar",
                                    "criadoEm": "2021-12-10T21:33:07.344Z"
                                }
                            }
                        }
                    }
                }
            },
            "responses": {
                "500": {
                    "description": "Internal Server Error"
                },
                "200": {
                    "description": "OK",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "$ref": "#/components/schemas/Beneficiados"
                            }
                        }
                    }
                }
            }
        }
    },
    "/users": {
        "get": {
            "tags": ["Beneficiados"],
            "summary": "Retorna todos os usuários",
            "description": "Retorna todos os usuários cadastrados",
            "parameters": [
                {
                    "name": "Beneficiários",
                    "description": "Retorna todos os beneficiários cadastrados",
                    "requestBody": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Beneficiados"
                                }
                            }
                        }
                    }
                }
            ],
            "responses": {
                "200": {
                    "description": "Operação realizada com sucesso",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "$ref": "#/components/schemas/Beneficiados"
                            }
                        }
                    }
                }
            }
        }
    },
    "/users/name": {
        "get": {
            "description": "Listar usuários pelo nome",
            "summary": "Listar os usuários por nome",
            "tags": ["Beneficiados"],
            "parameters": [
                {
                    "name": "Beneficiados",
                    "in": "query",
                    "busca": "Todos os usuários por nome",
                    "required": true
                }
            ],
            "responses": {
                "200": {
                    "description": "OK",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "$ref": "#/components/schemas/Beneficiados"
                            }
                        }
                    }
                }
            }
        }
    },
    "/users/update/:id": {
        "put": {
            "description": "Alterar usuários pelo ID",
            "summary": "Altera os usuários por ID",
            "tags": ["Beneficiados"],
            "parameters": [
                {
                    "name": "Alterar de Usuários por ID",
                    "in": "path",
                    "busca": "Altera os usuários por ID",
                    "required": true
                }
            ],
            "requestBody": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Beneficiados"
                        },
                        "example": {
                            "Beneficiados": {
                                "value": {
                                    "_id": "61b3c7936897b5137880ba5a",
                                    "name": "Leandro",
                                    "nickname": "Henrique",
                                    "email": "leandohq35@hotmail.com",
                                    "celular": 81998526547,
                                    "whatsapp": true,
                                    "bairro": "linha do tiro",
                                    "pix": "81998526547",
                                    "termosDeUso": true,
                                    "informacao": "Necessito de doações pois estou desempregado e tenho família para alimentar",
                                    "criadoEm": "2021-12-10T21:33:07.344Z"
                                }
                            }
                        }
                    }
                }
            },
            "responses": {
                "200": {
                    "description": "OK",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "$ref": "#/components/schemas/Beneficiados"
                            }
                        }
                    }
                }
            }
        }
    },
    "/users/delete/:id": {
        "delete": {
            "description": "Deletar usuário",
            "summary": "Deletar os usuários por ID",
            "tags": ["Beneficiados"],
            "parameters": [
                {
                    "name": "Deletar Usuários por ID",
                    "in": "path",
                    "busca": "Deleta os usuários por ID",
                    "required": true
                }
            ],
            "responses": {
                "204": {
                    "description": "No content",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "$ref": "#/components/schemas/Beneficiados"
                            }
                        }
                    }
                }
            }
        }
    },
    "/helpers/register": {
        "post": {
            "tags": [
                "Doadores"
            ],
            "summary": "Cria um cadastro de doadores",
            "description": "Criar um cadastro para as pessoas que querem ser doadoras",
            "requestBody": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Doadores"
                        }
                    }
                },
                "required": true
            },
            "responses": {
                "404": {
                    "description": "ERROR",
                    "content": {}
                },
                "200": {
                    "description": "Cadastro realizado com sucesso",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "objetc",
                                "$ref": "#/components/schemas/Doadores"
                            }
                        }
                    }
                }
            }
        }
    },
    "/helpers/private": {
        "get": {
            "tags": [
                "Doadores"
            ],
            "summary": "Retorna todos os doadores",
            "description": "Mostra o cadastro dos doadores",
            "parameters": [
                {
                    "name": "Doadores",
                    "description": "Retorna todos os doadores cadastrados",
                    "requestBody": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/Doadores"
                                }
                            }
                        }
                    }
                }
            ],
            "responses": {
                "200": {
                    "description": "Operação realizada com sucesso",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "$ref": "#/components/schemas/Doadores"
                            }
                        }
                    }
                }
            }
        }
    },
    "/helpers/name": {
        "get": {
            "description": "Listar usuários pelo nome",
            "summary": "Listar os usuários por nome",
            "tags": ["Doadores"],
            "parameters": [
                {
                    "name": "Doadores",
                    "in": "query",
                    "busca": "Todos os usuários por nome",
                    "required": true
                }
            ],
            "responses": {
                "200": {
                    "description": "OK",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "$ref": "#/components/schemas/Doadores"
                            }
                        }
                    }
                }
            }
        }
    },
    "/helpers/update/:id": {
        "put": {
            "description": "Alterar usuários pelo ID",
            "summary": "Altera os usuários por ID",
            "tags": ["Doadores"],
            "parameters": [
                {
                    "name": "Alterar de Usuários por ID",
                    "in": "path",
                    "busca": "Altera os usuários por ID",
                    "required": true
                }
            ],
            "requestBody": {
                "content": {
                    "application/json": {
                        "schema": {
                            "$ref": "#/components/schemas/Doadores"
                        },
                        "example": {
                            "Beneficiados": {
                                "value": {
                                    "_id": "61b3c7936897b5137880b89a",
                                    "name": "Leandro",
                                    "nickname": "Santos",
                                    "email": "leandosantos@hotmail.com",
                                    "termosDeUso": true,
                                    "criadoEm": "2021-12-10T21:33:07.344Z"
                                }
                            }
                        }
                    }
                }
            },
            "responses": {
                "200": {
                    "description": "OK",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "$ref": "#/components/schemas/Doadores"
                            }
                        }
                    }
                }
            }
        }
    },
    "/helpers/delete/:id": {
        "delete": {
            "description": "Deletar usuário",
            "summary": "Deletar os usuários por ID",
            "tags": ["Doadores"],
            "parameters": [
                {
                    "name": "Deletar Usuários por ID",
                    "in": "path",
                    "busca": "Deleta os usuários por ID",
                    "required": true
                }
            ],
            "responses": {
                "204": {
                    "description": "No content",
                    "content": {
                        "application/json": {
                            "schema": {
                                "type": "object",
                                "$ref": "#/components/schemas/Doadores"
                            }
                        }
                    }
                }
            }
        }
    }
},
"components": {
    "schemas": {
        "Beneficiados": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nickname": {
                    "type":"string"
                },
                "email": {
                    "type": "string"
                },
                "celular": {
                    "type": "number"
                },
                "whatsapp": {
                    "type": "boolean"
                },
                "cpf": {
                    "type": "number"
                },
                "bairro": {
                    "type": "string"
                },
                "pix": {
                    "type": "string"
                },
                "termosDeUso": {
                    "type": "boolean"
                },
                "informacao": {
                    "type": "string"
                },
                "criadoEm": {
                    "type": "string"
                }
            }
        },
        "Doadores": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "nickname": {
                    "type":"string"
                },
                "cpf": {
                    "type": "number"
                },
                "email": {
                    "type": "string"
                },
                "password": {
                    "type":"string"
                },
                "termosDeUso": {
                    "type": "boolean"
                },
                "criadoEm": {
                    "type": "string"
                }
            }
        }
    },
    "securitySchemes": {
        "bearerAuth": {
            "type": "http",
            "scheme": "bearer",
            "bearerFormat": "JWT"
        }
    }
}
}